name: BuyTempFly
main: org.crystal.buytempfly.Main
version: 1.0.0-SNAPSHOT
api-version: 1.16
depend:
  - Vault
  - TempFly
commands:
  btf:
    description: 购买飞行时间
    usage: /<command>
    permission: <plugin name>.btf
    permission-message: You don't have permission to do that
permissions:
  btf.*:
    description: BTF
    default: true